# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string
pool:
  name: 'default'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Docker@2
  displayName: Build
  inputs:
    command: build
    repository: enigmampc
    tags: enigma-sgx-node
    arguments: --build-arg SECRET_NODE_TYPE=NODE
- task: Docker@2
  displayName: Build
  inputs:
    command: build
    repository: enigmampc
    tags: enigma-sgx-node
    arguments: --build-arg SECRET_NODE_TYPE=BOOTSTRAP