# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string
pool:
  name: 'default'

steps:

- script: echo $(spid) > spid.txt; echo $(api-key-dev) > api_key.txt
  displayName: 'Save api keys'
- task: Docker@2
  displayName: Build
  inputs:
    command: build
    repository: ci-enigma-sgx-node
    tags: latest
    arguments: --build-arg SECRET_NODE_TYPE=NODE --build-arg SGX_MODE=HW
- task: Docker@2
  displayName: Build
  inputs:
    command: build
    repository: ci-enigma-sgx-bootstrap
    tags: latest
    arguments: --build-arg SECRET_NODE_TYPE=BOOTSTRAP --build-arg SGX_MODE=HW

- script: docker-compose -f docker-compose.ci.yaml up --exit-code-from node
  displayName: 'Run integration tests'

- script: docker-compose -f docker-compose.ci.yaml down
  condition: always()
  displayName: 'Shutdown'
