version: '3.4'

services:
  aesm:
    image: cashmaney/aesm
    devices:
      - /dev/sgx
    volumes:
      - /tmp/aesmd:/var/run/aesmd
    stdin_open: true
    tty: true

  node:
    image: cashmaney/secret-network-node:testnet
    devices:
      - /dev/sgx
    volumes:
      - /tmp/aesmd:/var/run/aesmd
      - /tmp/.enigmad:/root/.enigmad
      - /tmp/.enigmacli:/root/.enigmacli
      - /tmp/home:/root/
    environment:
      - SGX_MODE=HW
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:26657"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "26656:26656"
      - "26657:26657"